#!/usr/bin/env python3

from pathlib import Path
import subprocess

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "components/images/menu_system.png"
OUTPUT = ROOT / "components/images/menu_backups_accent.c"


def main():
    width, height = map(int, subprocess.check_output(
        ["magick", str(SOURCE), "-format", "%w %h", "info:"]
    ).split())
    rgb = subprocess.check_output(["magick", str(SOURCE), "-depth", "8", "RGB:-"])
    data = bytearray()
    for y in range(height):
        for start in range(0, width, 8):
            byte = 0
            for bit in range(8):
                x = start + bit
                offset = (y * width + x) * 3
                if x < width and rgb[offset:offset + 3] == bytes((255, 51, 153)):
                    byte |= 0x80 >> bit
            data.append(byte)
    rows = ["    " + ", ".join(f"0x{b:02x}" for b in data[i:i + 18]) + ","
            for i in range(0, len(data), 18)]
    OUTPUT.write_text(
        '#include "lvgl.h"\n\n'
        '// Generated by tools/generate_backups_accent.py from menu_system.png.\n'
        '// Recolor only the stock accent; preserve the frame, icons and chroma key.\n'
        'static const uint8_t Pixels[] = {\n' + "\n".join(rows) + '\n};\n\n'
        'const lv_img_dsc_t menu_backups_accent = {\n'
        '    .header.cf = LV_IMG_CF_ALPHA_1BIT,\n'
        f'    .header.w = {width},\n    .header.h = {height},\n'
        '    .data_size = sizeof(Pixels),\n    .data = Pixels,\n};\n'
    )
    print(f"Generated stock accent mask: {len(data)} bytes")


if __name__ == "__main__":
    main()
